### ISSUE TITLE
Rename `PostAllocate` to `Allocate` in Multi Cluster Allocation Service

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1331]
This came up in https://github.com/googleforgames/agones/pull/1314#discussion_r374386279

In this service:
https://github.com/googleforgames/agones/blob/master/proto/allocation/v1alpha1/allocation.proto#L22

We agreed that `Allocate` would be a nicer name to use.

**Comment by markmandel** [comment]
Thought I had - we could retain and deprecate PostAllocate for a release or two, and keep it alongside the new Allocate Service, to give people a smoother transition before removing it.

**Comment by pooneh-m** [comment]
The API is marked as alpha, which means there is no backward compatibility guarantee. This rpc method name change will not be the only breaking change and either we should support every breaking change or this will not be an exception. Because for V1 version the backward compatibility between alpha and v1 will not be carried over, I recommend breaking the API now and support backward compatibility on a stable version release.

**Comment by markmandel** [comment]
That's also fair. I would put it into the "best effort" bucket - if it's easy to do, awesome, if not, I don't have a strong opinion to maintain backward compatibility.

**Comment by pooneh-m** [comment]
It is easy to do, but IMHO it is unnecessary.
