### ISSUE TITLE
C++ SDK Cross compilation and testing

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#134]
## Problem 

Our current support for low dependency, cross compilation for the C++ SDK is very poor. Things work on Linux, because of `make` and not much else. We also have no tests.

Right now, the C++ SDK is built on top of [gRPC](https://grpc.io/), which may be adding too many dependencies to be used in a valuable way across platforms?

Code is here: https://github.com/GoogleCloudPlatform/agones/tree/master/sdks/cpp

## Requirements
1. Review the [current state of cross complication and dependency with gRPC](https://github.com/grpc/grpc/blob/master/src/cpp/README.md#make). 
1. Review the SDK [REST api endpoints](https://github.com/GoogleCloudPlatform/agones/blob/master/docs/sdk_rest_api.md), and see if that would be a better fit than connecting via gRPC.
1. Depending on that, prepare a design doc (added here is fine), with the following things in mind:
   1. Ability to cross compile on Linux/Mac/Windows
   1. Add some kind of unit tests, build tests, etc ideally with automation
   1. Anything else that is important to the C++ ecosystem (dependencies?)

Caveat: This is written by @markmandel who has little to no idea about C++ and its ecosystem, so direction on the above is also appreciated.

## Research
https://github.com/grpc/grpc/blob/master/src/cpp/README.md#make
https://www.appveyor.com
https://circleci.com/build-environments/xcode/osx/
https://docs.travis-ci.com/user/reference/osx/

[History](https://gist.github.com/markmandel/7e0adbb8141d1c862acba14bad63ed0d)

**Comment by SurferJeffAtGoogle** [comment]
[CMake](https://cmake.org/) is the defacto standard for building C and C++ code across platforms.

**Comment by markmandel** [comment]
Totally happy to have this rewritten with CMake (or whatever is appropriate) - I totally bashed this together with the help of someone with (somewhat?) more C++ experience than me, and this is an ecosystem I am very much not familiar with.

**Comment by dzlier-gcp** [comment]
[Notes doc](https://docs.google.com/document/d/1O7Je4cXMyNdUl_M28Qq3dcrWClHy3Vm-hdjglmsvyN4/edit) after meeting with rennie@, markmandel@ and myself.

**Comment by markmandel** [comment]
@martin-z-google This is the current state of the C++ SDK situation - please let me know if this makes no sense :smile:

**Comment by ortho** [comment]
Do you want to run protoc during build phase when using cmake or just want to compile current source using cmake (to make small step for cross building)?

**Comment by markmandel** [comment]
@ortho I think I understand the question? (I'm not 100% sure)

We generate the code from protoc and store it in  our github repo - since it's not going to change. We only change it when the .proto file changes -- and you can run `make gen-gameservers-sdk-grpc` to regenerate as needed.

Does that answer the question?

**Comment by markmandel** [comment]
@ortho - so right now, @martin-z-google is working on the first way. There are still runtime dependencies on protobuf's libraries, outside of the code generation (if i understand correctly, although martin can explain better than I can)

Personally, I'm not seeing any benefit in the second way -- it's not as if the generate code ever changes. But maybe I'm missing something?

**Comment by martin-z-google** [comment]
FYI pull request is up: https://github.com/GoogleCloudPlatform/agones/pull/421

**Comment by markmandel** [comment]
@alexandrem - do you have opinions here? You are my goto C++ person :smile: 

Or should we just get _something_ that works, and then we can iterate from there?

**Comment by dsazonoff** [comment]
I created a #464 pull request. It contain cmake scripts for cpp SDK.

**Comment by roberthbailey** [comment]
From the requirements in the initial issue comment, did anyone ever take a look into

> 2. Review the SDK REST api endpoints, and see if that would be a better fit than connecting via gRPC.

and write up rationale for continuing to invest in the gRPC wrappers?

**Comment by dsazonoff** [comment]
@roberthbailey I think that we should continue to use gRPC, because it is possible to have connection with most languages (even js). Nginx already supports forwarding of grpc traffic. And it is possible to create some kind of proxy over grpc->http, but I don't see any real cases when we may need it. But I'm not good in this area.

**Comment by markmandel** [comment]
Was digging through community build steps - found this, thought it might be interesting:
https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/windows-builder

**Comment by roberthbailey** [comment]
@dsazonoff - If the argument is about language support, then pretty much any language you'd encounter today will support sending an HTTP request. And since HTTP is a core part of the language, we don't need to worry about how well / long it is supported or compiler compatibility / etc. 

On the *server* side, I'm all in favor of grpc and http endpoints both being exposed. The question was more along the lines of whether it makes sense for the *clients* we build to depend on grpc or whether HTTP is sufficient as it is possible a smaller code.

**Comment by sylvainduchesne** [comment]
Both will work for the work, and admittedly HTTP is simpler to integrate. However, you need to poll for the GameSession status over HTTP, whereas that callback should come in automatically over gRPC. 

Personally, I don't find that convenience to be enough to warrant integrating gRPC on the client, since most codebases will already have HTTP clients integrated.

**Comment by roberthbailey** [comment]
I've marked this issue as stale. If you still find it relevant please leave a note, otherwise we will close it during our next round of triage.

**Comment by markmandel** [comment]
Closing, since it doesn't look like we have the capability to do this right now.
