### ISSUE TITLE
Alpha field in the stable API should follow best practices

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1347]
An [Alpha](https://github.com/googleforgames/agones/blob/master/pkg/apis/agones/v1/gameserver.go#L155) field is added but not following best practices of introducing an [unstable version to a stable API](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#adding-unstable-features-to-stable-versions):

* The field should be a pointer
* Use // +optional tag
* omitempty for GameServerStatus.Alpha
* Protected by feature gate for the API, storage and validation.

**Comment by markmandel** [comment]
Thanks for sharing this :+1: ! I went hunting for some kind of best practice here, and couldn't find one!
(Curious - where did you find this? This is a very strange url)

> The field should be a pointer

Sounds like a good idea. Let's do this.

// Use // +optional tag
Sounds good! Wondering what the change there will be to the generated client, but we will find out!

> emitempty for GameServerStatus.Alpha
I assume you mean `omitempty` ? We have this, but since it's not a pointer, it's probably not that useful.

> Protected by feature gate for the API, storage and validation.
Maybe we clear the Alpha state on "ApplyDefaults" if one exists? Since we can't directly control the storage since we are using CRDs and not a full API Extension.

I feel like creating new mutating webhooks to remove this value on update/create if they don't exist already might not be worth the effort.

How does that sound?

**Comment by pooneh-m** [comment]
> Thanks for sharing this  ! I went hunting for some kind of best practice here, and couldn't find one!
> (Curious - where did you find this? This is a very strange url)

I updated the URL to its origin.

> 
> > The field should be a pointer
> 
> Sounds like a good idea. Let's do this.
> 
> // Use // +optional tag
> Sounds good! Wondering what the change there will be to the generated client, but we will find out!
> 
> > emitempty for GameServerStatus.Alpha
> 
> I assume you mean `omitempty` ? We have this, but since it's not a pointer, it's probably not that useful.

We have it on GameServer.Alpha but not [GameServerStatus.Alpha](https://github.com/googleforgames/agones/blob/master/pkg/apis/agones/v1/gameserver.go#L228)
Thanks, yes I mean omitempty. :)

> 
> > Protected by feature gate for the API, storage and validation.
> 
> Maybe we clear the Alpha state on "ApplyDefaults" if one exists? Since we can't directly control the storage since we are using CRDs and not a full API Extension.

ApplyDefaults is a good idea and easy to implement.

> 
> I feel like creating new mutating webhooks to remove this value on update/create if they don't exist already might not be worth the effort.
> 
> How does that sound?

:+1:

**Comment by markmandel** [comment]
> We have it on GameServer.Alpha but not GameServerStatus.Alpha

Ah! Excellent catch! Good point.

Thanks for finding this - I was wondering how other groups solved this problem - this is great to know there is prior art we can leverage :raised_hands:
