### ISSUE TITLE
Document best practices for GameServer Allocation

### ISSUE THREAD

**Issue by pooneh-m** [googleforgames/agones#1594]
**Is your feature request related to a problem? Please describe.**
Right now there are three ways of allocating game servers; (1) K8sExtension API server using GameServerAllocate CRD; (2) agones-allocator service; (3) allocation SDK

**Describe the solution you'd like**
A best practices document is useful on what allocation solution to choose from.

**Comment by TBBle** [comment]
What's the allocation SDK? Is there now an SDK to go with the agones-allocator service, or are you referring to self-allocation via the (gameserver-facing) SDK? There already (well-buried) comparison of self-allocation with the `GameServerAllocation` flow at https://agones.dev/site/docs/guides/gameserver-lifecycle/.

Coincidental to #1590, I've been weighing up the pros and cons of moving from the k8s API to the agones-allocator service in our project for months, since we currently use the former, but everything else in our system is using REST APIs to other services so this is the only thing in our system that requires Kubernetes RBAC setup to function correctly, for talking to Agones. One team had some issues with the k8s API access permissions when deploying our project under Istio. So that's one comparison point.

Another comparison point is that if using the agones-allocator service, you still need to use k8s if you want to read things back from the resulting `GameServer` object, e.g. annotations set via the SDK. That's the reason we'll likely stay with using the k8s API.

**Comment by markmandel** [comment]
> What's the allocation SDK?
That's the `SDK.Allocate()` - you got it :+1:

**Comment by markmandel** [comment]
We have: https://agones.dev/site/docs/advanced/allocator-service/#gameserverallocation-vs-allocator-service

Is that enough for right now, or do you think we need more?

**Comment by pooneh-m** [comment]
That addition to the document addresses my feature request in this issue. So we can close this.

However, ideally we should have a section on https://agones.dev/site/docs/guides/gameserver-lifecycle/ that mentions agones-allocator to have a complete picture. I close the issue for now and if you also think we should be adding agones-allocator to [this](https://agones.dev/site/docs/guides/gameserver-lifecycle/), then open a new issue.
