### ISSUE TITLE
Ability to select which namespaces are managed by Agones

### ISSUE THREAD

**Issue by kdima** [googleforgames/agones#1670]
**Is your feature request related to a problem? Please describe.**
We are trying to reduce the number of services that have high level ClusterRoles i.e. ability to create pods, read secrets etc. We want to replace them with Roles that are namespace scoped. 

**Describe the solution you'd like**
To do this we would like to be able to specify which namespaces agones should look for/create resources in. Then we can create Roles in those namespaces and bind them to Agones service account.

**Comment by markmandel** [comment]
Thanks for your ticket! I'm not sure I 100% understand the request.

Can you explain how this is different from https://agones.dev/site/docs/installation/install-agones/helm/#namespaces ?

**Comment by robbieheywood** [comment]
@markmandel - it looks like the `gameservers.namespaces` Helm variable that you mention allows running gameservers in multiple namespaces by providing a service-account in each namespace with the required permissions - see [here](https://github.com/googleforgames/agones/blob/54f6a3885d7f4e7ced32b57ae9ba64f51dd0332c/install/helm/agones/templates/serviceaccounts/sdk.yaml#L15).

I believe what @kdima is mentioning is slightly different. Currently, the Agones controller has a service account with permissions to create pods in any namespace etc - see [here](https://github.com/googleforgames/agones/blob/54f6a3885d7f4e7ced32b57ae9ba64f51dd0332c/install/helm/agones/templates/serviceaccounts/controller.yaml#L300). This isn't ideal security-wise as, if someone were able to compromise the agones-controller, they could bring up a pod in any namespace (with any service-account attached) and therefore read any secret in the cluster.

It would be great if there was a way of restricting this [ClusterRole](https://github.com/googleforgames/agones/blob/54f6a3885d7f4e7ced32b57ae9ba64f51dd0332c/install/helm/agones/templates/serviceaccounts/controller.yaml#L30) to be a namespaced Role instead, so that we could only give Agones permissions to create pods in certain namespaces. For this, we'd need a way to indicate to the Agones controller to only look for gameservers in certain namespaces, rather than in all namespaces. This could potentially be done through a command-line argument (or environment variable) passed into Controller. What are your thoughts on this?

**Comment by aLekSer** [comment]
@robbieheywood Thanks for the detailed explanation. I think we should be more precise with a `ClusterRole` applied to Agones Controller. Possibly split out some of them to a namespaced `Role`.
And I think we could get rid of `namespace` field for `ClusterRole`s as it is misleading a bit:
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrole-example
I have tried the naive switching to see what would it lead to:
```
{"message":"agones.dev/agones/pkg/client/informers/externalversions/factory.go:119: Failed to list *v1.GameServerSet: gameserversets.agones.dev is forbidden: User \"system:serviceaccount:agones-system:agones-controller\" cannot list resource \"gameserversets\" in API group \"agones.dev\" at the cluster scope","severity":"error","time":"2020-07-06T08:41:31.80738084Z"}
{"message":"k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:agones-system:agones-controller\" cannot list resource \"pods\" in API group \"\" at the cluster scope","severity":"error","time":"2020-07-06T08:41:31.80741068Z"}
{"error":"customresourcedefinitions.apiextensions.k8s.io \"gameserversets.agones.dev\" is forbidden: User \"system:serviceaccount:agones-system:agones-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope","message":"could not start runner: *gameserversets.Controller","severity":"fatal","source":"main","time":"2020-07-06T08:41:31.80747281Z"}
```

**Comment by aLekSer** [comment]
I made a sketch solution with limiting the Pods and Secrets permissions to the namespace `"default"` for Agones Controller.
https://github.com/aLekSer/agones/tree/poc/controller-rbac-restricted-pods-secrets
There would be a loop to create `NewSharedInformerFactoryWithOptions` for each `namespace` used for `GameServers`. Note that this solution is much more safe.
Note that there would be a need to restart `Agones Controller` each time we update `gameservers.namespaces` using helm.

**Comment by robbieheywood** [comment]
@aLekSer - the spike on your branch looks really good. The new Roles replacing the ClusterRole would certainly fit our use-case 👍

**Comment by markmandel** [comment]
@robbieheywood thanks for the detailed explanation - that's make a lot of sense.

> There would be a loop to create NewSharedInformerFactoryWithOptions for each namespace used for GameServers. Note that this solution is much more safe.

This makes me feel like it's going to be super ugly code wise, but I can't think of a better solution.

Maybe it's worth building an abstraction that sits in front of a `SharedInformerFactory` that has the same interface, but can watch multiple namespaces. Just to make our lives easier?

**Comment by aLekSer** [comment]
>Maybe it's worth building an abstraction that sits in front of a SharedInformerFactory that has the same interface, but can watch multiple namespaces. Just to make our lives easier?
Thanks for such an interesting approach, will try to implement this.

**Comment by markmandel** [comment]
Talking about this in the community meeting:

Seems like a good first step would be to change the RBAC rules in the Helm config, and report on what breaks in the Agones controller.

Ideally, nothing breaks, and it's an easy switch over - since we're already telling Agones which namespace it has access to for the SDK Service Accounts.
