### ISSUE TITLE
Unity Game Server Client SDK

### ISSUE THREAD

**Issue by uweenukr** [googleforgames/agones#1809]
"The Unity SDK is not feature complete in 1.2.0, but will be feature complete with the 1.3.0 release."

Can anyone familiar with the project state verify if this warning statement is still valid? If so any information regarding what is missing?

**Comment by roberthbailey** [comment]
Hi @uweenuk. 

We should definitely update that note (which is from https://agones.dev/site/docs/guides/client-sdks/unity/) since it refers to pretty old releases at this point. 

https://github.com/googleforgames/agones/issues/927 tracks the status of getting the various SDKs to be feature complete. From that issue, it looks like Unity is just missing conformance tests. However, since that issue was created we've added alpha SDK APIs, which are not yet supported by the Unity SDK. So it's still lagging a bit behind some of the other SDKs in terms of being feature complete. 

Many of our SDKs are primarily maintained by community members that use them, and if you are interested in using the Unity SDK and contributing to it we would also love that. :)

**Comment by markmandel** [comment]
I think we can remove that warning though - since we have all the stable features?

Thanks for pinging us on it, totally missed that one.

**Comment by roberthbailey** [comment]
Agree on removing the warning (I just wanted to give a heads up on the overall feature status, since that was also asked).

**Comment by markmandel** [comment]
Yeah, that 100% makes sense.
