### ISSUE TITLE
Update metrics documentation

### ISSUE THREAD

**Issue by robbieheywood** [googleforgames/agones#1851]
**What happened**:

`agones_grpc_io_server_server_latency_bucket` isn't documented in the metrics page at https://agones.dev/site/docs/guides/metrics/.

**What you expected to happen**:

https://agones.dev/site/docs/guides/metrics/ is updated to include all current metrics

**How to reproduce it (as minimally and precisely as possible)**:

Go to https://agones.dev/site/docs/guides/metrics/

**Anything else we need to know?**:

n/a

**Environment**:
- Agones version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
@robbieheywood if you can work out what this metric is for, we would love a pull request! 😃

**Comment by gongmax** [comment]
It's not a documentation issue since Agones doesn't expose such a metric named "agones_grpc_io_server_server_latency_bucket". Or do you mean [`grpc.io/server/server_latency`](https://github.com/googleforgames/agones/blob/main/vendor/go.opencensus.io/plugin/ocgrpc/server_metrics.go#L30)?

Closing this for now. Please reopen if you think Agones is missing some metrics that should be exposed. Thanks.
