### ISSUE TITLE
Move Default CRD values to Schema from MutationWebHook

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1934]
**Is your feature request related to a problem? Please describe.**
We do all our defaulting through Mutation Webhooks - which is an extra http request and JSON serialisation/deserialisation which we could potentially do away with.

**Describe the solution you'd like**

Now that we structural schemas in CRDs, we can use defaulting where possible and hopefully get rid of some mutation webhooks.
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting

**Describe alternatives you've considered**

We could leave it as is. It is handy in unit test to be able to say things like `GameServer.ApplyDefaults()` - which we would no longer be able to do.

Also, if it doesn't totally do away with a mutation webhook, it might not be worth the effort.

**Additional context**

https://github.com/googleforgames/agones/search?q=ApplyDefaults

**Comment by roberthbailey** [comment]
Use the schema defaulting sounds like a big improvement to me. It makes things simpler and allows us to leverage the built in validation and defaulting behavior (and presumably would make it easier to do multiple CRD versions as well).

**Comment by cindy52** [comment]
Looks like most of the default cannot be applied automatically with the schema. The openapi validation default doesn't have the feature to add if condition for the default and the property name must be defined for the default (meaning we can't apply default for an annotation map)

Here are some examples showing the if condition needed for applying default.
https://github.com/googleforgames/agones/blob/e048859c6ff3da0d4b299f915113993aa49c7865/pkg/apis/agones/v1/fleet.go#L126
https://github.com/googleforgames/agones/blob/e048859c6ff3da0d4b299f915113993aa49c7865/pkg/apis/agones/v1/gameserver.go#L286
https://github.com/googleforgames/agones/blob/e048859c6ff3da0d4b299f915113993aa49c7865/pkg/apis/agones/v1/gameserver.go#L293

And annotation examples as following:
https://github.com/googleforgames/agones/blob/e048859c6ff3da0d4b299f915113993aa49c7865/pkg/apis/agones/v1/fleet.go#L140
https://github.com/googleforgames/agones/blob/e048859c6ff3da0d4b299f915113993aa49c7865/pkg/apis/agones/v1/gameserver.go#L252

I would suggest a `won't fix` for this bug since we still need to keep most of the ApplyDefaults() methods.
@markmandel @roberthbailey

**Comment by markmandel** [comment]
> I would suggest a `won't fix` for this bug since we still need to keep most of the ApplyDefaults() methods.
> @markmandel, @roberthbailey please suggest. Thanks!

I did wonder if our defaulting would be too complex for the OpenAPI schema. Thanks for digging into things! I agree with your conclusion above. Any objections with moving to `wontfix` and closing @roberthbailey ?

**Comment by roberthbailey** [comment]
No objections from me. Thanks for digging into this @cindy52!
