### ISSUE TITLE
There are so many options to do things in the documentation, we need some tips/insights on which one we would use and why. 

### ISSUE THREAD

**Issue by MeltdownInteractive** [googleforgames/agones#1964]

**Comment by MeltdownInteractive** [comment]
I'm reading through the docs at the moment, and while they are well written and informative, they can feel a little overwhelming with all the options to do things.

For instance, on this page
https://agones.dev/site/docs/installation/creating-cluster/

We have 4 different options to create a cluster, but I have no idea why there are 4 options, or which option would suit me best, or for which stage my integration is at. 

A couple of other pages in the docs once again give many other options, but some context behind each option would be welcome.

Thanks!

**Comment by markmandel** [comment]
Thanks for the feedback!

To set some context, have you gone through https://agones.dev/site/docs/prerequisite-knowledge/ yet?

**Comment by roberthbailey** [comment]
I think adding a short blurb to the description for minkube on the create page would make sense. For the other solutions, the choice generally follows from the cloud provider you are using, but explaining why minikube is there seems reasonable (the answer is that it is an easy getting started experience since it is local dev & free). 

For the gke page, what did you think about the the section ["Choosing a shell"](https://agones.dev/site/docs/installation/creating-cluster/gke/#choosing-a-shell)? Cloud shell comes with the tooling preinstalled (gcloud, kubectl, and even helm) which means less configuration. So it's an easy way to get started if you don't want to spend time configuring a bunch of stuff on your local machine.

**Comment by markmandel** [comment]
I think we can close this issue? It's been stale for over a year now.

Any objections?

**Comment by markmandel** [comment]
Closing this since it was marked as stale back in June.
