### ISSUE TITLE
Add HTTPS support for agones-ping-http-service

### ISSUE THREAD

**Issue by kaboing** [googleforgames/agones#2117]
**Is your feature request related to a problem? Please describe.**
To be able to support WebGL projects that are hosted in https-environments, all outgoing requests from a WebGL client build needs to be https to avoid mix-environment problems. "Pinging" the agones-ping-http-service is perfect to to determine what region to connect to when having multiple clusters deployed over the globe. 

**Describe the solution you'd like**
Https support for agones-ping-http-service. Add port 443 and proper TLS support, probably with ListenAndServeTLS() function. 

**Describe alternatives you've considered**
I don't think there are any alternatives on how to expose the latency-check-service for an http-enironment.

**Comment by markmandel** [comment]
🤔 Given that this is probably going to need to be tied to a domain -- I'm wondering if this falls outside the purview of Agones, and moves it into `wontfix` territory, as there are many tools that are far better suited for this work.

Some thoughts:

1. Use a Cloud HTTP/S load balancer/GKR ingress for each endpoint. They have the capabilities to serve domains, and also to be able to provision SSL certs. I've no done it, but something like [Setting up HTTP(S) Load Balancing with Ingress](https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer) seems like a good place to start.
2. If you want to go fully open source, a nginx proxy (or similar) with lets-encrypt would likely also do the job.
3. There's probably some other ways of doing this I'm not aware of, utilising some kind of other proxy/load balancing layer.

Otherwise we have to build in a stack of cert management features that I don't think we want to take on the maintenance burden for.

@roberthbailey any thoughts on your end?

**Comment by kaboing** [comment]
Yes, thanks for pointing out the different options! I do agree that we should burden agones with cert-handling. I'll muse a bit if there's something to add to the agones documentation about how to get https for the ping endpoint. 
I'll close the issue.
