### ISSUE TITLE
Change monolithic yaml to kustomization

### ISSUE THREAD

**Issue by Jeffwan** [googleforgames/agones#2202]
**Is your feature request related to a problem? Please describe.**

I feel monolithic yaml is not that easy to manage, for example, If I like to update images allocator or control image. It's hard to easily override them.  Another example is to customize namespace 

**Describe the solution you'd like**
Since kustomization has been built into kubectl . Can you use `kubectl apply -k install/yaml` to install the manifests?

We can change the folder structure to 
```
.
├── base
│   ├── cluster-role-binding.yaml
│   ├── crd.yaml
│   ├── .......
│   └── kustomization.yaml
└── overlays
    └── production
    └── dev
        └── kustomization.yaml


# dev override. 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  component: agnoes
images:
  - name: gcr.io/agones-images/agones-allocator
    newTag: 1.17.0-7d287f4

```

**Describe alternatives you've considered**

**Additional context**

Do you think that's a reasonable request? If so, I can help contribute to it.  I am pretty new to Agones and also let me know your practice.

**Comment by markmandel** [comment]
We currently provide customisation through Helm tooling: https://agones.dev/site/docs/installation/insall-agones/helm/

Are there any issues or blockers you are having with this approach?

We also use helm to output the index.yaml, so we don't have the capability to split things up at this point, but you can always output your own index.yaml from helm with the your options provided if you don't want to use Helm specifically.

**Comment by Jeffwan** [comment]
> We currently provide customisation through Helm tooling: https://agones.dev/site/docs/installation/insall-agones/helm/
> Are there any issues or blockers you are having with this approach?

No blockers, this still work for us but bring extra stack (helm). I am not a helm lover  :D but this definitely works for us. 

> We also use helm to output the index.yaml, so we don't have the capability to split things up at this point, but you can always output your own index.yaml from helm with the your options provided if you don't want to use Helm specifically.

Yeah, that means helm template is an entrypoint to add customization support. Since agnoes has different ways for installation. I think it makes sense to maintain a "source of truth".  


I will do some research to see if helm can be used to generate kustomization. that would be interesting.

**Comment by roberthbailey** [comment]
The [yaml install](https://agones.dev/site/docs/installation/install-agones/yaml/) is meant to make it super easy to get up and running and kick the tires. It doesn't offer any customization (by design) and is entirely machine generated. 

We have a number of users that use the [helm install](https://agones.dev/site/docs/installation/install-agones/helm/) for customization. You don't have to actually use helm as your deployment tool. Plenty of folks just use helm to render the customized yaml installation and then apply that to their cluster using their deployment tool of choice.

**Comment by roberthbailey** [comment]
> I will do some research to see if helm can be used to generate kustomization. that would be interesting.

This would be neat, since it would solve the problem more generally. If you look at our helm templates, they are broken up similarly to what you would see with kustomize. 

One of the nice things about the way our install yaml is structured right now is that it provides a single source of truth (the helm configuration). When we want to add new parameters to customize the install process, we only have to add them in one place (and [document them in one place](https://agones.dev/site/docs/installation/install-agones/helm/#configuration)). 

Having a new auto-genreated output from the helm configs would be neat. It _may_ also be acceptable to make kustomize the source of truth as long as you could then auto-generate the helm configuration from the kustomize files, if that is easier and/or on the roadmap for one of those projects.

**Comment by Jeffwan** [comment]
I agree. Consider the maintenance efforts and complexity of agones yaml, "source of truth" is important to make manifest consistent. I will go to helm community to see if we can build some convertors for future usage.
