### ISSUE TITLE
When NodeIp only has InternalIp, is it possible to provide a third way to expose services, such as through LB (VIP: VPort)?

### ISSUE THREAD

**Issue by youngwang3** [googleforgames/agones#2226]
**Is your feature request related to a problem? Please describe.**
When an Agones is deployed privately and NodeIp only has InternalIp, the existing port exposure method cannot be accessed outside the cluster

**Describe the solution you'd like**
When an Agones is deployed privately and NodeIp only has InternalIp, is it possible to configure an LB according to yaml to access through LB (VIP: VIP: VPort) -> GameServerPod

**Describe alternatives you've considered**
When an Agones is deployed privately and the NodeIp only has InternalIp, GameServerAllocation can only get the InternalIp: Port of a GameServer, but it is still inaccessible outside the cluster. Therefore, consider mapping this GameServerPod: LB VIP: VPort to DS Container Port, so that the Client can access through VIP: VPort.

**Additional context**
clinet->LB->GameServerPod

**Comment by markmandel** [comment]
If I'm understanding this correctly, I'm not sure it's possible. This sounds like something that should be managed outside of Agones.

Some thoughts/questions:

We can't be creating a load balancer for every game server, and the extra latency doesn't make sense there either.

Not sure what a "VIP" or "VPort" here is - can you explain that?

I'm not sure I'm reading any kind of solution here. If a node is private, it can't be exposed - so that's on you to determine how it should be exposed. I'm not sure what we should actually do here?

What is this mapping? How would it work? It sounds like it's something you need specific to your use case? It doesn't sound like something generic -- which makes me (at least initially) think that this doesn't belong in the Agones project -- but please expand more, I'd like to completely understand the use case before drawing a conclusion.

**Comment by roberthbailey** [comment]
This issue hasn't been updated in a while so I'm going to mark it as stale.

**Comment by roberthbailey** [comment]
I will also note that in the time since this question was asked, [Quilkin](https://cloud.google.com/blog/products/gaming/introducing-quilkin) has added support to be a udp proxy for Agones game servers, which may help solve this sort of problem.

**Comment by markmandel** [comment]
We have #2001 for writing some more docs on websockets, so to close this out, why don't we add a link to Quilkin and it's examples/docs to https://agones.dev/site/docs/third-party-content/examples/ and we can close his issue.

**Comment by Kalaiselvi84** [comment]
Please review this PR and let me know if there's anything I can improve - https://github.com/googleforgames/agones/pull/3129
