### ISSUE TITLE
Flaky:  make run-sdk-conformance-test-cpp

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2346]
**What happened**:

The cpp sdk-conforformance test has been flaky for a while.

**What you expected to happen**:

Pass every time

**How to reproduce it (as minimally and precisely as possible)**:

Run in CI? 😞 it's flaky, so it's been super hard to track down.

**Anything else we need to know?**:

I did notice this one line in the most recent failure:
https://console.cloud.google.com/cloud-build/builds/e5dfe61f-bfe1-46b2-8782-4a84f241c144?project=258182270954

```
Shutting down after 10 seconds...
Could not run Shutdown():Connect Failed. Exiting!
terminate called without an active exception
/root/sdktest.sh: line 18:     9 Aborted                 (core dumped) /go/src/agones.dev/agones/test/sdk/cpp/.build/.bin/cpp-simple
includes/sdk.mk:88: recipe for target 'run-sdk-command' failed
```

**Environment**: Linux
- Agones version:  dev
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: Google Cloud
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): (see above)
- Others:

Please add more if you see other failures.

**Comment by markmandel** [comment]
My current theory on this: The build server is congested, and sometimes the local sdk code can't complete in 30s, so the local sidecar times out, and then the test fails.

**Comment by roberthbailey** [comment]
Is this the same as https://github.com/googleforgames/agones/issues/2298?

**Comment by markmandel** [comment]
Unfortunately I can't tell - the logs no longer exist.

**Comment by roberthbailey** [comment]
What do you think about splitting up the sdk conformance steps in cloudbuild into discrete steps instead of a single step.

The main advantage that I see is that it separates the logs for each step, making it clear _which_ step (or steps) failed and what logs apply - should help with debugging. 

The disadvantage is that when we add new tests, instead of just updating the makefile target we will also need to add a step to cloudbuild so that CI tests all of the sdks. 

Given that we aren't seeing much churn in SDKs at this point, I think the advantages of debugging outweigh the additional maintenance upkeep. WDYT?

**Comment by govargo** [comment]
I updated TIMEOUT to 40s in https://github.com/googleforgames/agones/pull/2580#issuecomment-1137414284.

And I haven't seen this error this month.
Could we close this issue and https://github.com/googleforgames/agones/issues/2298?

**Comment by markmandel** [comment]
I haven't seen this in ages either.

I can't believe that was the simple fix! This flakey test bugged us for years.

I vote to close the issue. @roberthbailey any objections?

**Comment by roberthbailey** [comment]
None from me - we can re-open or create a new issue if the flake arises again.
