### ISSUE TITLE
Migrate to use prow GitHub app instead of bot account

### ISSUE THREAD

**Issue by chaodaiG** [googleforgames/agones#2347]
**Is your feature request related to a problem? Please describe.**

Part of https://github.com/GoogleCloudPlatform/oss-test-infra/issues/1171

OSS prow currently uses bot personal access token(PAT) for authentication with GitHub APIs, which has a global rate limit of 5000 per hour. This is not very well scalable with many tenants. Switching over to GitHub app will get a rate limit per installation, which would greatly increase the rate limit exhaustion problem we have seen lately

**Describe the solution you'd like**

Install Google OSS Prow app on corresponding org/repo https://github.com/apps/google-oss-prow

OR

I'm not seeing much prow activity going on in this repo, so if it's not used any more, might be a good opportunity to remove the footprints? Please comment on this issue to let me know if this is the case, I will take care of the cleanup.

**Comment by chaodaiG** [comment]
Any update yet?

**Comment by roberthbailey** [comment]
We'd been fighting some flaky tests so that got put onto the back burner. I plan to look at it next week.

**Comment by roberthbailey** [comment]
I've installed the prow app into the `googleforgames` org (so that we can use it in other repos too) by going to https://github.com/apps/google-oss-prow, clicking `Configure` and select the `googleforgames` org.

That took to me https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/onboarding.md?installation_id=20615503&setup_action=install -- but this looks like it might be the old instructions? Can you advise on next steps and also if there is cleanup that I should do for the old prow permissions (e.g. can I delete the PAT now)?

**Comment by chaodaiG** [comment]
Hi Robert,

Thank you so much! I have confirmed that it was installed. I'll take care
of the rest, and there are no more actions from your end.

- Chao

**Comment by chaodaiG** [comment]
Thank you so much! I have confirmed that it was installed. I'll take care of the rest, and there are no more actions from your end.

The PAT is still used in other places of prow, I'll handle the migration in the background, and let you know when it's safe to remove the PAT

**Comment by roberthbailey** [comment]
Sounds good. Feel free to reopen this ticket or create a new one when the time comes.
