### ISSUE TITLE
Fleet specific prometheus metrics should stop being exported when the fleet is deleted

### ISSUE THREAD

**Issue by luna-duclos** [googleforgames/agones#2478]
**What happened**: When you run an agones controller for a very long amount of time, you end up with a pile of metrics for every fleet that was created since the controller has started, the metrics endpoint exports each of them as an individual line, and lines always keep being piled on and are never cleared. 
This is a problem if you end up running a controller for a very long time (say, 90 days) and start a lot of fleets (say, 20 a day).
The latency bucket type metrics end up with ... a loooooot of lines which make the prometheus agent use more memory than it should be for no reason as it has no idea the data is useless.

**What you expected to happen**: Once a fleet is deleted, agones should keep it in the metrics endpoint long enough for it to be scraped by prometheus, and after that the line shold be removed

**How to reproduce it (as minimally and precisely as possible)**: Just run the controller and create a fleet

**Anything else we need to know?**: This is an open discussion, but I don't think this fix has any downsides, the same happens when the agones controller is restarted.

**Environment**:
- Agones version: 1.19
- Kubernetes version (use `kubectl version`): 1.21.6-gke.1500 
- Cloud provider or hardware configuration: Both GCP and AWS
- Install method (yaml/helm): Helm 
- Troubleshooting guide log(s): None
- Others:

**Comment by luna-duclos** [comment]
> 

15 minutes is probably a good tradeoff even for folks with very long scrape timers I recon ?

**Comment by markmandel** [comment]
SGTM.

**Comment by markmandel** [comment]
Making a note that while we are in here, we should do the same thing for FleetAutoscalers as well (since it's all together).

**Comment by markmandel** [comment]
I've got a POC working for Fleets (I basically have to unregister then register the entire `View` to reset it's values and then rebuild it after a Fleet gets deleted -- but it's kludgy, but it gets the job done.

Not sure if I'll get to both Fleets and Fleet allocations before RC on Tuesday, but I reckon I can probably round off at at least Fleet 🤞🏻 I'll try my best.

**Comment by markmandel** [comment]
Was digging into this more, and decided I didn't want to rush things, but wanted to get feedback on my approach before going deeper, so this fix is going to roll into the next release cycle.

You can see the code in:

* #2626 

## Constraints

OpenCensus doesn't provide a way to remove part of Gauge metric - you can only reset the whole thing back to a zero state and rebuild. That means that, if we have two fleets, and that provides the following metrics for `agones_fleets_replicas_count`:

```
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="simple-game-server", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="allocated"}
0
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="simple-game-server", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="desired"}
2
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="simple-game-server", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="ready"}
2
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="simple-game-server", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="reserved"}
0
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="simple-game-server", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="total"}
2
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="xonotic", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="allocated"}
0
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="xonotic", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="desired"}
2
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="xonotic", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="ready"}
2
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="xonotic", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="reserved"}
0
agones_fleets_replicas_count{agones_dev_role="controller", app="agones", heritage="Helm", instance="10.100.13.15:8080", job="kubernetes-pods", kubernetes_namespace="agones-system", kubernetes_pod_name="agones-controller-657fc8c7b6-khqfq", name="xonotic", namespace="default", pod_template_hash="657fc8c7b6", release="agones", type="total"}
2
```

There's no way for to _just_ get rid of the metrics for where `name="xonotic"` and still leave the metrics for `name="simple-game-server"` - but I can reset (basically remove and the add back in again) the entirety of `agones_fleets_replicas_count`, and then rebuild.

## Approach

The code in the draft PR does the following on Fleet Deletion:
1. Fleet is immediately dropped to a 0 zero count for all fields.
2. A timer is started, and then in 15 minutes, `agones_fleets_replicas_count` is cleared, and the count for every Fleet in the system is counted and published.
3. If another Fleet is deleted within the time in which No. 2's has started, a new timer is started, but the original continues to run.

The implication is, If FleetA is deleted, and then 14:55 minutes later FleetB is deleted, the FleetB will be removed from `agones_fleets_replicas_count` 5 seconds later.

## Questions

So to those of you who are actually using these metrics, I ask:

* Does that matter?
* Is there a better approach?
* If it doesn't matter, should we reset all metrics for Fleets immediately (thereby removing that Fleet from all the metrics), rather than wait 15 minutes?

## Alternatives considered

* Don't wait 15 minutes, just reset the metrics straight away
* If FleetB is deleted before the 15 minutes for FleetA's deletion runs out - reset the resync timer to 15 minutes again. (In theory this could end up with never resetting if Fleets are quickly added and removed, but is that likely?)

Would love your thoughts.

**Comment by markmandel** [comment]
> but maybe someone else is and would need that configuration variable set to 15m. I'd be setting ours to 0.

The only reason I can think of for someone to want it to be set to something like 15m, is that they want to catch that the Fleet is now at `0` counts for everything.

But if that is super important, then we have to implement the strategy that if a Fleet gets deleted it pushes out the timer by 15 minutes (or configurable value) if there is one running already, since we have to allow time for the metrics system to capture the most recently deleted Fleet.

It's definitely much simpler on our end if we wipe everything at the time that a Fleet is deleted.

**Comment by luna-duclos** [comment]
Hmmm 🤔 
We delete and create fleets a lot, so for us it's actually a little bit trickier, though I don't imagine in practice it's going to be an issue.
I'm somewhat surprised though, opencensus really should be allowing a reset of particular lines ...

An alternative suggestion could be that we clear fleet metrics every 24 hours and rebuild it with only currently active fleets ?
This would avoid this issue entirely while still fixing the problem.

**Comment by markmandel** [comment]
Okay, this is my final thought:

I'm going to implement this as "reset all stats on Fleet deletion immediately" - I think it's the simplest solution with the least number of edge cases. 

But I'll put it behind a feature flag. That way, you can try it out, see how it goes, and if we find problems, you can always turn it off / and we can adjust if we need to.

Sound good?
