### ISSUE TITLE
helm_agones module for Terraform doesn't support setting variables

### ISSUE THREAD

**Issue by junekhan** [googleforgames/agones#2484]
**What happened**:
Tried to change LoadBalancerIP in module.tf(EKS) and got an error

**What you expected to happen**:
```
╷
│ Error: Unsupported block type
│ 
│   on module.tf line 95, in module "helm_agones":
│   95:   set {
│ 
│ Blocks of type "set" are not expected here.
```

**How to reproduce it (as minimally and precisely as possible)**:
```
module "helm_agones" {
  // ***************************************************************************************************
  // Update ?ref= to the agones release you are installing. For example, ?ref=release-1.17.0 corresponds
  // to Agones version 1.17.0
  // ***************************************************************************************************
  source = "git::https://github.com/googleforgames/agones.git//install/terraform/modules/helm3/?ref=main"

  udp_expose             = "false"
  agones_version         = var.agones_version
  values_file            = ""
  feature_gates          = var.feature_gates
  host                   = module.eks_cluster.host
  token                  = data.aws_eks_cluster_auth.example.token
  cluster_ca_certificate = module.eks_cluster.cluster_ca_certificate
  log_level              = var.log_level

  set {
    name  = "agones.allocator.service.loadBalancerIP"
    value = "HostNameHere"
  }
}
```

**Anything else we need to know?**:
BTW, can I set hostname instead of IP address to `agones.allocator.service.loadBalancerIP`

**Environment**:
- Agones version: 1.21.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by roberthbailey** [comment]
> BTW, can I set hostname instead of IP address to `agones.allocator.service.loadBalancerIP`

I don't believe so. That parameter gets used for the `loadBalancerIP` field in the allocator service spec [here](https://github.com/googleforgames/agones/blob/main/install/helm/agones/templates/service/allocation.yaml#L58) and if I'm reading the [kubernetes docs](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer) correctly, it looks like it has to be an ip address. 

The main reason to set this parameter is if you are connecting to the allocator service by its IP address - then setting this parameter tells the helm chart to generate a TLS cert that includes this IP as a valid SAN. If you are connecting by a DNS name instead, then your allocator service with need that name in the cert instead of the service IP.

**Comment by markmandel** [comment]
Looking at our terraform helm variables: https://github.com/googleforgames/agones/blob/main/install/terraform/modules/helm3/variables.tf

We don't have it setup this way (I wonder how/if you can without writing code?) It does look like the `LoadBalancerIP` is not a variable that has been added, but a PR to include it would be appreciated, and solve your issue 👍🏻
