### ISSUE TITLE
Failure calling webhook for creating a fleet

### ISSUE THREAD

**Issue by emrys90** [googleforgames/agones#2485]
There's some kind of race condition for after Agones is installed through yaml using
kubectl create namespace agones-system --kubeconfig kubeconfig
kubectl apply -f https://raw.githubusercontent.com/googleforgames/agones/release-1.21.0/install/yaml/install.yaml --kubeconfig kubeconfig

Before I can then call
kubectl apply -f ./ci/kubernetes/fleet.yaml --kubeconfig kubeconfig

If its called too soon I get this error:
Error from server (InternalError): error when creating "./ci/kubernetes/fleet.yaml": Internal error occurred: failed calling webhook "mutations.agones.dev": Post "https://agones-controller-service.agones-system.svc:443/mutate?timeout=10s": dial tcp 10.128.182.57:443: i/o timeout

I'm trying to set up automated deploys. How can I know when Agones is ready for the fleet to be created? Kubectl apply call doesn't seem to return any error code, so I also don't know if it succeeded or failed except by manually checking the logs

**Comment by roberthbailey** [comment]
Check out https://agones.dev/site/docs/installation/confirm/

After you apply the yaml file, the agones components need to be up and running before you can create fleets. You can write a simple script to automate the checks on that page (which I've done, but I don't remember where I put it). 

@markmandel - adding such a script to our docs / repo would probably be useful.

**Comment by markmandel** [comment]
The other answer to this - is use helm with `--wait` command (which is one of the reasons that Helm exists), which will ensure that everything is up and running appropriately before exiting.

> @markmandel[](https://teams.googleplex.com/markmandel@google.com) - adding such a script to our docs / repo would probably be useful.

Maintaining it might be harder though, since in theory, Agones parts could move around at any point and time.

If you are strongly wanting to stick to installing via `install.yaml`, the other option is to [bash script some retry logic](https://stackoverflow.com/questions/5274294/how-can-you-run-a-command-in-bash-over-and-over-until-success
) into your `kubectl apply` command, to run several times until it passes. Something like (off the top of my head, check for correctness):

```bash
sleep 5
until kubectl apply -f ./ci/kubernetes/fleet.yaml --kubeconfig kubeconfig
do
   sleep 5
done
```

Could also build in a `max_retries` if you desired, if your CI doesn't have a timeout option.

**Comment by emrys90** [comment]
Thank you! Adding --wait to the helm install worked fine
