### ISSUE TITLE
Is it possible for in-place or hot update of sdkserver sidecar in gameserver's pod?

### ISSUE THREAD

**Issue by scarlet25151** [googleforgames/agones#2492]
**Is your feature request related to a problem? Please describe.**

I'm building a long running `GameServer`, during it's lifecycle there may be a demand from my SRE team that we need to update the `agones-sdk-server` from `1.16.0` to `1.20.0`. Since it's a sidecar container's update and we don't want restart a new `GameServer`'s Pod, is there any possible for hot update or at least in-place update of a sidecar container without interfering the main container in a GameServer's Pod?
  
**Describe the solution you'd like**

Hot update or In place update for `agones-sdk-server` , we can assigned a version of `agones-sdk-server` container and when we can modify the image version for updating without restart the Pod in a GameServer's lifetime.

**Describe alternatives you've considered**

I don't think it a good practice that to split the `agones-sdk-server` sidecar with the main container. But if we split the sidecar, and just start the main container, we have some components like sidecar manager can inject the `agones-sdk-server`  to Gameserver's Pod when starting and do the hot/in-place update stuff.
 
**Additional context**

**Comment by roberthbailey** [comment]
This doesn't answer your question, but I'm curious what your plan is if the Node on which the long running game server exists needs to be updated (security patches, Kubernetes update, etc). At that point you will need to evict all running pods from the node so that it can be upgraded / replaced. 

The reason I ask is that depending on the frequency of node updates vs. Agones updates, could you do them at the same time? This would side step the need to try and implement a system to update one container in a pod without disturbing the other container.

**Comment by markmandel** [comment]
I think my short answer for this is: No, this is not possible, nor would we likely consider it a possibility.

We've always stayed away from live-updates of Agones, because it's just a straight nightmare, and the inherent complexity of testing is verging on impossible due to the almost limitless array of update paths.

My suggestion: Bake into your game/infra a way to do occasional host migrations / game server drains into your matchmaker for when you need to do upgrades across your entire system (because at some point, as @roberthbailey pointed out, you will need to shut down nodes eventually).

**Comment by scarlet25151** [comment]
Thank you both for great answer and suggestion of hosting an update or migration for our game system. We may consider the strategy of the system update. And I think this issue can be closed.

**Comment by markmandel** [comment]
No worries! Glad to help 👍🏻
