### ISSUE TITLE
About metrics in dashboard-goclient-caches.yaml

### ISSUE THREAD

**Issue by ctanaka-aim** [googleforgames/agones#2529]
We are currently trying to build agones prometheus,Grafana.
Grafana uses the template under this directory.
https://github.com/googleforgames/agones/tree/main/build/grafana

However, I cannot get the metrics used in dashboard-goclient-caches.yaml.
 (For example, agones_k8s_client_cache_last_resource_version )

The dashboard metrics in dashboard-allocations.yaml would not have shown up without the actual Allocation, but
In the same way, do I have to actually do something to see it?

I also checked to see if agones_k8s_client_cache_last_resource_version is actually output from prometheus, but it doesn't seem to be.

Environment:
Agones version: 1.21.0
Kubernetes version (use kubectl version): 1.21.10-gke.1300
Cloud provider or hardware configuration: GKE
Install method (yaml/helm): helm

**Comment by markmandel** [comment]
So it looks like it comes from here:
https://github.com/googleforgames/agones/blob/f725d023f600a89a879c7cba4180daa632fa77da/pkg/metrics/kubernetes_client.go#L124-L129

Which is part of the interface passed to client-go and the workerqueue to expose metrics that it exports.

Since the metric is called from the client-go code, we can't control when it actually happens - is it a metric that you are relying on?
