### ISSUE TITLE
We should automatically reject PR's that are not against `main`

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2531]
**What happened**:

We had a PR submitted against a `release-*` branch, and nobody noticed, and it was merged.

See: https://github.com/googleforgames/agones/pull/2528

**What you expected to happen**:

It should automatically fail a check, and prevent the merge (unless overwritten by admin permissions).

**How to reproduce it (as minimally and precisely as possible)**:

File a PR against a `release-*` branch.

**Anything else we need to know?**:

Doesn't seem like branch protection will solve this problem. My initial thought is to write a Github action that checks the PR is against main, and fails if it's not.

**Environment**: N/A
- Agones version:  N/A
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): N/A
- Troubleshooting guide log(s):  
- Others: N/A

**Comment by markmandel** [comment]
Another note - we should add a note to our contributing guide to tell people to submit PR's against `main`.

**Comment by roberthbailey** [comment]
There are a bunch of [settings you can enable for protected branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#about-branch-protection-settings) and it looks like we may not have had any of them enabled. 
* We could set "Require pull request reviews before merging" to require **multiple** users to approve a PR (rather than one) which may help catch cases where the PR is targeted at a branch. 
* We could also change the "Include administrators" setting to make restrictions apply to administrators, which may allow us to "Restrict who can push to matching branches" to no one (although that section says that "People and apps with admin permissions to a repository are always able to push to a protected branch" which seems to be in conflict with the prior setting). 
* To prevent the case where admins could inadvertently push a PR to a release branch we could enable "Require signed commits" and since we don't normally expect or require signed commits this may provide another failsafe to remind us that we should only push to the main branch. 

Another option is to use a merge queue tool to automatically handle merges (of all PRs) and configure it to never merge into anything except for main.

**Comment by markmandel** [comment]
Oooh, that's some clever ideas!

Combine several (I'm figuring a quick solution is best, since this doesn't come up very often)?

![image](https://user-images.githubusercontent.com/298370/161624116-5d2f8dca-f70c-4ce6-8065-7c3897587d5c.png)

**Comment by markmandel** [comment]
Gentle bump - how do we feel about these changes?

**Comment by roberthbailey** [comment]
I'm in favor of them. I don't think they will affect most contributors but will prevent maintainers from accidentally merging PRs to the wrong branch.

**Comment by markmandel** [comment]
Sounds good, will make the changes shortly.

**Comment by markmandel** [comment]
Applied to the release branch! Clsoing.
