### ISSUE TITLE
Explore the impact of K8s API Priority and Fairness

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#2648]
Context:
https://kubernetes.io/docs/concepts/cluster-administration/flow-control/

This feature is in beta, and enabled from K8s 1.20 onwards.

Summary

> Controlling the behavior of the Kubernetes API server in an overload situation is a key task for cluster administrators. The [kube-apiserver](https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver) has some controls available (i.e. the --max-requests-inflight and --max-mutating-requests-inflight command-line flags) to limit the amount of outstanding work that will be accepted, preventing a flood of inbound requests from overloading and potentially crashing the API server, but these flags are not enough to ensure that the most important requests get through in a period of high traffic.

> The API Priority and Fairness feature (APF) is an alternative that improves upon aforementioned max-inflight limitations. APF classifies and isolates requests in a more fine-grained way. It also introduces a limited amount of queuing, so that no requests are rejected in cases of very brief bursts. Requests are dispatched from queues using a fair queuing technique so that, for example, a poorly-behaved [controller](https://kubernetes.io/docs/concepts/architecture/controller/) need not starve others (even at the same priority level).

We should explore if/what the impact is on Agones since we do a _lot_ of K8s API requests, since we're so churny on the cluster.

From what I can tell, as operator author, I don't think we have much control. If I'm understanding this correctly - the `FlowSchema`  defines which underlying operations on the cluster get each amount of share - by service account, resource type, type of request, etc, and then maps that back to a `PriorityLevelConfiguration` which says how much of the total requests (`--max-requests-inflight` and `--max-mutating-requests-inflight`) on the cluster are allowed. All of this is set by the cluster admin - I have yet to try, but I don't think we can edit it.

Anyway, we should run some tests, see what we can see. If nothing else, it may produce some documentaiton.

**Comment by zmerlynn** [comment]
I'll try to look into this soon.

**Comment by zmerlynn** [comment]
I did a little research this afternoon:
* Our controllers, and anything with a service account vs just a random interactive user, fall into the `workload-low` bucket (at least on GKE, and [by suggestion](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#suggested-configuration-objects).
* `workload-low` has by far the large concurrency share on GKE, with 100 shares out of ~250. Even `workload-high` only has 40 shares (presumably because it is less overall QPS, but we still want a dedicated "lane" for it).
* We definitely have the ability (on GKE at least) to mutate `PriorityLevelConfiguration` and add `FlowSchema`.

In evaluating APF, we need to ask: do we need a dedicated lane for Agones? IMO, this breaks down to two separate questions:


### Does the Agones control plane need to be protected from other workload traffic? 
Is Agones so critical that interference from other controllers would disturb Agones? IMO, no. Looking at the things we have sharing the `workload-high` lane, for instance, they're all critical controllers. `workload-low` ain't no slouch, either - it's got a large share already.

### Do other workloads need to be protected from Agones? 
Is Agones so chatty that we might starve out other controllers? Well! Here we can lean on the fact that Agones was been operating for several releases while APF has been rolling out, and any critical system controllers have likely been protected from its chattiness already (by e.g. moving into `workload-high`). That mostly leaves 3rd party controllers - but our users tend to run single-use Agones controllers vs mixed workloads. IMO, this is not worth protecting, either.

### My $0.02

The `FlowSchema` and `PriorityLevelConfiguration` have already been tuned to a reasonable point and are meant to be useful "out of the box" for almost all workloads. I think this might be something we adopt a wait-and-see approach on - if there are users that APF would clearly help, we can work with them 1:1 and then see if a pattern develops.
