### ISSUE TITLE
I doubt controller portAllocations newPortAllocation will conflict

### ISSUE THREAD

**Issue by alvin-7** [googleforgames/agones#2735]
**It is confused for me, thank you for your answer**

**What happened**:
give gs Allocate a hostport will conflict?
I find allocate hostport use pa.portAllocations what not distinguish node name, then will in conflict with has allocation hostport in same node.

**What you expected to happen**:
Maintain a node portAllocations to allocate what allocate hostport for same node name to slove conflict. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.25.0
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration: N/A
- Install method (yaml/helm): N/A
- Troubleshooting guide log(s): N/A
- Others: N/A

**Comment by zmerlynn** [comment]
Hey, I read this code recently enough that I think I can answer - but I don't think I quite understand the problem here. When we reconcile, we definitely track the node name, here: https://github.com/googleforgames/agones/blob/418aff0c6a4fdd702c6f0b7ad72f4accc1c0ee91/pkg/gameservers/portallocator.go#L340-L353

But that gets immediately put into just an array in https://github.com/googleforgames/agones/blob/418aff0c6a4fdd702c6f0b7ad72f4accc1c0ee91/pkg/gameservers/portallocator.go#L290

The reason why it's fine as an array is that we don't really care what node the game server lands on, we're just trying to keep the port space as dense as we can by spreading the ports out as much as possible. So during allocation, the sets are effectively just buckets of available ports that happen to originally be tied to nodes (when we first reconcile) but don't need specific assignment later. Further, they can't even be specifically assigned. Where the port allocator runs is right before pod creation and the scheduler hasn't even assigned a node yet.

In reality, this structure is kind of a confusing way to keep the allocation. I _think_ the allocation as it stands today could be kept as a simple array of counts, i.e. {port} => {number of times port has been assigned}.

If you see an actual bug here, please reopen. Otherwise, I am closing this. Thanks for the help!
