### ISSUE TITLE
Improve uniqueness of the namespace in the codes generated from protobuf schema.

### ISSUE THREAD

**Issue by s-shin** [googleforgames/agones#2753]
**Is your feature request related to a problem? Please describe.**
Currently [the protobuf package name of the AllocationService is set to `allocation`](https://github.com/googleforgames/agones/blob/v1.26.0/proto/allocation/allocation.proto#L17) so that the root namespace of the generated code for C# (and also other languages) is just [`Allocation`](https://github.com/googleforgames/agones/blob/v1.26.0/examples/allocator-client-csharp/Program.cs#L6). I think it should contain  the unique element such as `Agones.Allocation`.

**Describe the solution you'd like**
We can declare namespace options and/or add a prefix to the package name (e.g. `agones.allocation`) like [googleapis](https://github.com/googleforgames/agones/blob/v1.26.0/proto/googleapis/google/api/annotations.proto#L17-L26), but will have to think about backward compatibility.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by roberthbailey** [comment]
This feels like it could be a breaking change. If we change the namespace of the proto package, would a client using the new package be able to successfully connect to the allocator service running an older release of Agones? Or vice versa?

Since the code paths would be identical, it might be possible to host old & new side by side for a few releases to mitigate compatibility issues. 

How much of a usability issue do you find this to be? Do you think that fixing it is worth figuring out a solution to the backwards compatibility issues?

**Comment by s-shin** [comment]
> If we change the namespace of the proto package, would a client using the new package be able to successfully connect to the allocator service running an older release of Agones? Or vice versa?

Setting the namespace by option might not affect the behavior but according to [this answer](https://stackoverflow.com/a/47654538), changing the package name could cause a breaking change.

> How much of a usability issue do you find this to be? Do you think that fixing it is worth figuring out a solution to the backwards compatibility issues?

This is not a critical issue for me now and I think it would be good to fix this in major update in the future.

A bit weird scenario I thought is that if a user created `MyProject.Allocation.Something` class, he/she may need to write such as `global::Allocation.AllocationRequest`, make an alias of it by `using`, or customize the proto files.
