### ISSUE TITLE
No gameservers available when lots of requests in quick succession

### ISSUE THREAD

**Issue by ZakShearman** [googleforgames/agones#2788]
**What happened**: Allocator returns `There are no available servers to connect you to. Try again later or contact an admin.` when rapidly requesting for gameserver allocations

**What you expected to happen**: Allocator would return a `lobby-x-x` pod's details. 

**How to reproduce it (as minimally and precisely as possible)**: Rapidly request to the allocator for allocations.

**Anything else we need to know?**:

I am accessing the allocator externally using the gRPC API

Code that gets an allocation: <https://github.com/towerdefence-cc/server-discovery/blob/main/src/main/java/cc/towerdefence/api/serverdiscovery/controller/ServerOrchestratorController.java#L26>

The allocator logs the following: 
```
{"error":"Could not find an Allocatable GameServer","gsa":{"metadata":{"namespace":"towerdefence","creationTimestamp":null},"spec":{"multiClusterSetting":{"policySelector":{}},"required":{},"selectors":[{"matchLabels":{"agones.dev/fleet":"lobby"},"gameServerState":"Allocated","players":{}},{"matchLabels":{"agones.dev/fleet":"lobby"},"gameServerState":"Ready","players":{}}],"scheduling":"Packed","metadata":{}},"status":{"state":"","gameServerName":""}},"gsaKey":"towerdefence/","message":"failed to allocate. Retrying...","severity":"warning","source":"*gameserverallocations.Allocator","time":"2022-11-01T22:27:26.321631464Z"}
```

It appears that if I scale to 5 lobby servers, every lobby server will be allocated two players. As a result, 10 players will be able to join before others logging in within quick succession are rejected.

When scaling up to 15 lobby servers, every lobby server was allocated 1 player and as a result, 15 players were kicked as no available server could be found.

**Environment**:
- Agones version: 1.27.0
- Kubernetes version (use `kubectl version`): 1.25.3 (k3s)
- Cloud provider or hardware configuration: Testing on a 6 core, 64GB RAM server
- Install method (yaml/helm): Helm
- Troubleshooting guide log(s): 
- Others:

**Comment by markmandel** [comment]
Sorry, I'm 100% quite sure I fully get the issue here -- can you expand further on what the state of GameServers are at each step, and what you expect to happen?

My _guess_ is that when all your Ready GameServers are Allocated, on quick request, the Allocated GameServers have yet to be updated in the Allocation cache, so the system isn't aware they exist yet, and therefore your first selector fails, and there are no Allocation yet.

Is that correct?

**Comment by ZakShearman** [comment]
This may also help demonstrate the issue a bit better. The bot program makes a player join every 100ms and as you can see, a majority of them fail (due to no GameServer being found). However, some of them do succeed throughout (so it seems as if there's some kind of ratelimit?)

https://user-images.githubusercontent.com/34372536/199780617-9bf85d67-c8da-46fa-85f1-8fdf806440df.mp4

**Comment by markmandel** [comment]
I think I follow the issue here, and I think it's a question of expectation, which I 100% understand.

Basically for performance and scale reasons, the query cache for allocation is eventually consistent (which we should document better), so it is entirely possible that while you do have room in a GameServer, the Allocation query cache may not be aware of it straight away.

So at high load, and a small number of GameServers, this can definitely get exacerbated.

Some solutions:
1. Have more GameServers, so there is more capacity.
2. Implement your own backoff and retry (with Jitter) on Allocations on top of what Agones already does. I'd be tempted to backoff by a second +jitter even on first retry, just to give the system some room to breath.

**Comment by ZakShearman** [comment]
Ahh ok yh that does make sense.

My expectation was that I could allocate maybe 10/20 players to a server within a second but it totally makes sense. Some additional documentation would definitely help.

 Thanks for the help.

**Comment by markmandel** [comment]
I'll reopen this as a reminder to update the docs 👍🏻 this came up on Slack the other day as well.
