### ISSUE TITLE
FleetAutoScaler scalingLimited is reporting the incorrect state

### ISSUE THREAD

**Issue by Dinhh1** [googleforgames/agones#2828]
**What happened**:
It seems as though the scalingLimited attribute of an autoscaler is incorrectly reporting it's state.

**What you expected to happen**:
I expect scalingLimited = false when the number of gameservers < the maxReplicas 

**How to reproduce it (as minimally and precisely as possible)**:

1.  Configure an autoscaler with: max - 50, min - 10, buffer - 5
2. Allocate 1 or 2  GameServers
3. Observer how scalingLimited is set to true even though we're below our max replica threshold
![image (3)](https://user-images.githubusercontent.com/5686945/204336051-9b2495bf-8d03-4c4c-b117-81b0f0b59fbf.png)

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.26
- Kubernetes version (use `kubectl version`): 1.24
- Cloud provider or hardware configuration: AWS EKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others: Original Slack Thread: https://agones.slack.com/archives/C9DGM5DS8/p1668793997712099

**Comment by oniku-2929** [comment]
I also met the same situation in my EKS and Minikube environment.
Then I did a little research and test about it.

In conclusion, I guess it's expected behavior. 
Because this flag is exposed as a "scale-in & scale-out" Limited flag.
I misunderstood it's a "scale-out" Limited flag.

In pkg/fleetautoscalers/fleetautoscalers.go `func applyBufferPolicy`
https://github.com/googleforgames/agones/blob/9f430b8cebb1c501c838873c16b4195e95a503a6/pkg/fleetautoscalers/fleetautoscalers.go#L193-L226
This `limited` flag is exposed as a Prometheus metric "agones_fleet_autoscalers_limited" and then we can see it as a "Scaling Limited" flag on Grafana.

In the above situation,
>1.Configure an autoscaler with: max - 50, min - 10, buffer - 5
>2.Allocate 1 or 2 GameServers

Initially, the replicas count is 0(no allocation) + 5 = 5.
then replicas fix to 10(MinReplicas) and will be limited for avoiding scale-in.

still, the same adjustment happens after 1 or 2 GameServers allocations.
So "Scaling Limited" is True.

on "Metrics" Page.
https://agones.dev/site/docs/guides/metrics/
>agones_fleet_autoscalers_limited	The fleet autoscaler is capped (1)

I think it would be helpful to add "scale-in or scale-out is limited based on the fleet autoscaler's setting" in the description for avoiding such a misunderstanding.

I couldn't see the Slack Thread that is mentioned above.
So I don't understand any details about it on Slack.

**Comment by markmandel** [comment]
Reading above, I'm not 100% sure if this is actually an issue 🤔 

That being said, please investigate and let us know if you can confirm either way.

**Comment by markmandel** [comment]
Or to be clearer - are you looking to update the code or the docs? (Sounds like the docs **do** need an update!)

**Comment by atgane** [comment]
I will update docs!
