### ISSUE TITLE
Unity SDK - switch to using syntax for Webrequests

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2830]
**Is your feature request related to a problem? Please describe.**
Unity recommends the "using" syntax for Webrequests to prevent issues like https://github.com/googleforgames/agones/pull/2822 and guarantee a nicer cleanup: https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.Dispose.html. 

**Additional context**
/cc @davidyrgilbert

**Comment by gongmax** [comment]
C# 8.0 introduced the [using declaration feature](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using) that makes it a little more easy and clean.

**Comment by austin-space** [comment]
Just as a note, C# 8.0 was only introduced as of Unity 2020.3. Introducing C# 8.0 features would move the [currently stated supported unity version](https://github.com/googleforgames/agones/blob/4b4b6284a2fff56d0afea3b231d53ab0c17892d3/site/content/en/docs/Guides/Client%20SDKs/unity.md#prerequisites). That being said, 2020.3 appears to be the [oldest supported version for now](https://endoflife.date/unity), so that might not be a problem.
