### ISSUE TITLE
Unreal Engine - Ability to Unwatch Game Server

### ISSUE THREAD

**Issue by pixovr-mgruber** [googleforgames/agones#2939]
**Is your feature request related to a problem? Please describe.**
WatchGameServer was added recently to the Unreal Engine plugin, but there is no way to stop watching the game server.

**Describe the solution you'd like**
A function called something like UnwatchGameServer that allows me to pass the original FGameServerDelegate to have it removed from the Array WatchGameServerCallbacks.

**Describe alternatives you've considered**
I've added a flag in my class and the callback that prevents it from running when I no longer need to watch the game server.

**Additional context**
I'm implementing a function that calls a series of SetLabels with metadata to set on the Agones server that allows us to set configured and runtime metadata that isn't otherwise easily available to Agones and can change build to build. Currently just using an AgonesComponent, WatchGameServer is the only way for us to determine when the server is ready and available for us to call SetLabel. We only need to watch till the server is Ready and execute the code once per server.

**Comment by markmandel** [comment]
🤔  this seems unnecessary to need to switch in and out of being able to watch a gameserver config.

Can't you do the Unreal version of something like:

```
var checked = false;
SDK.WatchGameServer(func (gameserver) {
   if !checked && gamserver.status.state = "Ready" {
      // do the things
     checked = true;
  }
});
```

And not worry about it anymore? 

(Unless unreal has some kind of atomic `DoOnce` construct?, kind of like https://pkg.go.dev/sync#Once )?

**Comment by Titantompa** [comment]
I'd like to second this request...

While the periodic refreshes causes a minor bump in the server framerate, which is undesirable, the bigger problem for us lies in how the Unreal SDK is implemented and that there seems to be no valid way for the client (gameserver) to close this connection without causing error messages from the sidecar.

From what I gather the sidecar only has support for establishing connections, by design, and expects them to never go away throughout the lifecycle of both parties. So even though it is intuitive that you'd be able to simply close the websocket to stop receiving updates, the sidecar doesn't have any support for handling any sort of disconnect. Not even involuntary failures.

Thus, I fail to see a way to do server travels without ending up with error messages in the log that in other situations would be alarming.  (And also having the SDK change the state of the server to _Ready_, even though it is already _Allocated_. But that is a different issue.)

**Comment by markmandel** [comment]
> Thus, I fail to see a way to do server travels

Can you explain what a "server travel" is please?
