### ISSUE TITLE
Not able to get allocated and scheduled time for gameservers

### ISSUE THREAD

**Issue by oll-aroundarmor** [googleforgames/agones#3395]
Issue: I was trying to get metrics for gameserver in prometheus by using `agones_gameserver_state_duration_sum` but it is providing me values for agones-controller/fleet allocated and scheduled state.

What I want: I want to get the agones-sdk metrics in order to get the details for how much time an individual gameserver was in an allocated and scheduled state.

Help-needed:
1. Suggestion if there is any way through which I can get those metrics to reflect for individual gameservers.
2. Is there a way I can get a service and service monitor for agones-sdk?

Any suggestions would be greatly appreciated.

**Comment by markmandel** [comment]
Thanks for the question!

> Suggestion if there is any way through which I can get those metrics to reflect for individual gameservers.

You can't get at individual GameServer metrics as metrics are aggregate values.

If you want to watch individual GameServers, I recommend writing some small code to interact with the Kubernetes API:
https://agones.dev/site/docs/guides/access-api/

> Is there a way I can get a service and service monitor for agones-sdk?

Sorry, not quite sure what you mean by this - can you expand on it in more detail?

**Comment by markmandel** [comment]
>  If I can get the service and service monitor for agones-sdk I will be able to get the metrics for individual gameservers from agones_gameserver_state_duration_sum.

Sorry I don't follow how this approach works? Metrics are aggregated, they aren't per GameServer, and you don't really want to do this, because metric services can't handle combinatoric explosion with an essentially infinite number of labels.

I'll put it another way - getting per-GameServer information out of metrics is going to be a non starter.

Watch the Kubernetes API for GameServer changes to do this. Or use the Event stream, that would work as well.
