### ISSUE TITLE
Missing agones_k8s_client_cache_* metrics

### ISSUE THREAD

**Issue by Kalaiselvi84** [googleforgames/agones#3540]
**What happened**:

Setup of a GKE Autopilot cluster with Agones was completed, and Prometheus was configured for collecting metrics. During the setup of Grafana dashboards, it was observed that the `agones_k8s_client_cache_*` metrics are missing. These metrics are not present in the Prometheus exports from the `/metrics` endpoints of any services.

**What you expected to happen**:

Expected the agones_k8s_client_cache_* metrics in Grafana dashboards

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

It's possible that the metrics exported from client-go have changed. Relevant code is here, in case you want to take a look: https://github.com/googleforgames/agones/blob/e5d89bc2f47c6a34662c6afa6f1a057e250f81a8/pkg/metrics/kubernetes_client.go#L199C8-L199C35

**Environment**:
- Agones version: 1.36.0
- Kubernetes version (use `kubectl version`): 1.28
- Cloud provider or hardware configuration: GKE Autopilot

**Comment by markmandel** [comment]
Just noting that I'm seeing this in GKE standard, as well - I don't think it's an autopilot issue - I think something changed in client-go somewhere.

**Comment by markmandel** [comment]
One day I'd like to work out what went wrong here.

**Comment by vicentefb** [comment]
I've been researching and looked up closely at [`cache.SetReflectorMetricsProviders(c)`](https://github.com/googleforgames/agones/blob/e5d89bc2f47c6a34662c6afa6f1a057e250f81a8/pkg/metrics/kubernetes_client.go#L199C8-L199C35) line of code. I found that there was an issue where the [metric was empty](https://github.com/kubernetes-sigs/controller-runtime/issues/817) 

Additionally, it was removed from Kubernetes as seen here https://github.com/kubernetes/kubernetes/pull/74636 due to a memory leak. 

So it makes me wonder if this is the reason why we don't see it anymore in Prometheus...

**Comment by markmandel** [comment]
Ah. If it's been removed entirely, we should probably drop the Grafana dashboard and any docs we have.

Is there an easy way we can confirm this? or do we just take it as a given?

**Comment by vicentefb** [comment]
They also "recently" (April of this year) mentioned it here https://github.com/kubevirt/kubevirt/pull/11184#issuecomment-2042672930 which confirms that it was deprecated in Kubernetes. So I think we can take it as a given and remove anything related to this metric...

**Comment by markmandel** [comment]
Seems reasonable to me.
