### ISSUE TITLE
fleet controller maybe need a state cache

### ISSUE THREAD

**Issue by keisni** [googleforgames/agones#3555]
https://github.com/googleforgames/agones/blob/69efac2751b124ec3cf7e7d0ad97731195ff126d/pkg/fleets/controller.go#L298-L316

identical active GameServerSet could be created in such cases:
1. rolling update begin, the code here create a new active gss for the new template.
2. some rest gss updated, and the reconcile loop here runs agagin.
3. the add event for the created active gss has not been received, so another gss with the new template is created.

the duplicated gss will be deleted after a while, due to eventual consistency. but maybe we should avoid this situation with a state cache like the one used in gss controller?

**Comment by markmandel** [comment]
> the duplicated gss will be deleted after a while, due to eventual consistency. but maybe we should avoid this situation with a state cache like the one used in gss controller?

How often does this actually happen though? 🤔 and it would only happen on Fleet creation or update -- so is this a micro-optimisation that moves us away from our usual pattern for eventual consistency and self healing? (i.e is the bang worth the buck?)

My initial thought is that this would be a micro-optimisation that's probably not worth it, but I'm willing to be convinced otherwise 😄

**Comment by keisni** [comment]
Yeal, just a discusstion，you can close it.

**Comment by markmandel** [comment]
Sounds good, I'll close. Thanks for poking through the code though!
