### ISSUE TITLE
https and CORS for agones-ping http service

### ISSUE THREAD

**Issue by devcube9** [googleforgames/agones#3864]
**Is your feature request related to a problem? Please describe.**
It would be great if we can measure and compare latency of agones clusters in the browser. Currently, all http requests to the http ping service would fail due to CORS. The requests would also fail if the game client is served via https

**Describe the solution you'd like**
Allow CORS and possibly https on http ping service

**Describe alternatives you've considered**
Create a custom ping service

**Additional context**
This is used for multiplayer browser games

**Comment by markmandel** [comment]
This feels like the sort of thing that could done with NGINX or Envoy etc.

I'm leaning towards us adding HTTPs handling into the Allocator service was a not-great idea, since there are so many better ways to handle certs, etc with proxies / service meshes.

So I'm inclined to say `wontfix`, since this is solvable with other, better tools.
