### ISSUE TITLE
Move Feature GKEAutopilotExtendedDurationPods to Beta

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#3930]
Prerequisites:
* #3919 

Once the above is completed, our lowest supported K8s version will be 1.28.x, so we should be able to bump this to beta.

**Comment by markmandel** [comment]
@zmerlynn - any objections to the above?

**Comment by zmerlynn** [comment]
`AutopilotPassthroughPort` just went to Beta after the last release, @vicentefb did that in #3916

However, because you're referencing k8s version numbers, did you perhaps mean `GKEAutopilotExtendedDurationPods`?

I would still like `GKEAutopilotExtendedDurationPods` to go through `Beta` and not go straight to `Stable`, and we may want it to hang out in `Beta` for several releases as it changes the default scheduling policies on Autopilot for all Agones pods.

**Comment by markmandel** [comment]
Blerg, I missed this one several levels 🤦🏻‍♂️

1. Yes I meant `GKEAutopilotExtendedDurationPods`
2. Yes, I meant moving to Beta.
3. I did just also realise that `AutopilotPassthroughPort` is listed as alpha at https://agones.dev/site/docs/guides/feature-stages/#feature-gates 

So, updated ticket, and also any issue with moving to Beta.

**Comment by zmerlynn** [comment]
No objection now. :)

**Comment by markmandel** [comment]
@ashutosji this one is ready to go!

**Comment by zmerlynn** [comment]
> @ashutosji this one is ready to go!

Well, it's ready to go *after #3919*, as mentioned above. :)
