### ISSUE TITLE
Create npm package for Node.js sdk

### ISSUE THREAD

**Issue by msannikov** [googleforgames/agones#679]

**Comment by rorygarand** [comment]
I'll put in a PR for this. I'd really like to use npm for my project.

**Comment by rorygarand** [comment]
Actually it looks like all that's really needed is access to Google's npm account. I'd love to help out if I can. Ping me if that's the case.

**Comment by markmandel** [comment]
Could we / should we use https://github.blog/2019-05-10-introducing-github-package-registry/ ?

Or should we have our own npm package? (I've no idea about this ecosystem)

**Comment by rorygarand** [comment]
Interesting. That would definitely work, but in my mind it's more a question of how Google handles (or wants to handle) packages they maintain.

I'm not sure if it matters to anyone at any level whether developers install agones via:

```sh
$ npm install @github/agones
```
vs.

```sh
$ npm install @google/agones
```

**Comment by markmandel** [comment]
I think we could have an agones specific account - we don't necessarily need to have it tied to google itself.

**Comment by rorygarand** [comment]
I'm agnostic about the approach. The github package registry is pretty neat but it is invite-only at the moment.

If adding to the npm registry is as simple as someone creating an account, I don't mind managing that.

Getting the project into either registry would make my life easier so let me know what I can do to help.

**Comment by markmandel** [comment]
@thisisnotapril what's the common practice for this kind of thing? (storing account credentials for external repositories, etc?)

**Comment by rorygarand** [comment]
@markmandel @thisisnotapril any updates on this? i'm currently forking the repo so i can maintain my own registry through github with this as a package. 

I wouldn't mind taking ownership of pushing to the googleforgames registry whenever there are version updates, since I'm already doing that anyways for myself, but I think I would need some access credentials to the repo that maybe you don't want to give to a rando off the internet.

I can also walk someone else through the process, or write something up etc. It's not terribly difficult but would make dev a little easier for my team. Currently we have to manually ensure we're all on the same version of agones locally before deploying.

**Comment by markmandel** [comment]
Hey! We should totally do this. Let's push it to [this repository](https://github.com/googleforgames/agones/packages).

What would be ideal for me :smile: is to have a Makefile target I can add to our release process.
Somewhere in here would likely be ideal:
https://github.com/googleforgames/agones/blob/master/build/includes/release.mk

Then I don't even need to know how NPM works! :smile: 

The tricky bit would be you would need to use the [npm sdk image](https://github.com/googleforgames/agones/blob/master/build/build-sdk-images/node/Dockerfile) - but there is a [run-sdk-command-node](https://github.com/googleforgames/agones/blob/master/build/includes/sdk.mk#L66) target that should make this quite easy!

I'm happy to do the part to integrate it into `do-release` part (since I usually test out releases anyway).

If you need to grab a Github token from the command line to authenticate, there is an example above as well.

Let me know if you need any help navigating the build system, either here or on Slack!

How does that sound?

**Comment by markmandel** [comment]
I'll ask this question, since it's probably worth asking, since I've no idea about the node ecosystem.

Better to host the npm package on github or on npmjs? (Github is easier for us, as there is only 1 auth system to manage)

**Comment by rorygarand** [comment]
That sounds perfect, I'll start on this right away. 

I personally feel that npm vs github doesn't matter. The only problem this is solving for is keeping version numbers consistent across the team in a unified way.

**Comment by rorygarand** [comment]
@markmandel this can be closed now.

**Comment by markmandel** [comment]
Excellent point! Closed!

**Comment by phumberdroz** [comment]
I just wanted to integrate this but I have a couple of concerns.

My Plan was to publish a module for an existing game that other developers that modify that game as well can just integrate my solution. 
My concern: every developer/machine(CI/CD) would now need to authenticate with GitHub to download this package and the package I would like to build.
This introduces a complexity that is currently not really common in open source JS.
See: [Install from Github registry](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-npm-for-use-with-github-packages#installing-a-package)

The npm registry works without authentication and no need for manual settings.

Please consider publishing this into the NPM registry

**Comment by rorygarand** [comment]
Agreed. I admit that when we started working on this, I had only published packages to github that were intended to be private. When it came to this project, I expected that authentication would not be required because this repo is public.

Now that the package is live I'm also experiencing the same sort of issue. 

@markmandel I know this was just released, and I told you npm vs github didn't matter for the registry, but would this be something we could explore? There would be a couple of changes to what we just did but the overall build process would be the same.

**Comment by markmandel** [comment]
That makes a lot of sense - sounds like I should setup a [npm](https://www.npmjs.com/) account for Agones? Probably setup an Agones org, yes?

**Comment by phumberdroz** [comment]
You would want an NPM account and I would recommend to create an Org with that account and publish packages under that org.

**Comment by markmandel** [comment]
@thisisnotapril should we do an Agones org, or a GoogleforGames org?

**Comment by thisisnotapril** [comment]
We have a Google org already; let's explore using that one.

**Comment by markmandel** [comment]
That makes sense - likely https://www.npmjs.com/package/@google-cloud/

**Comment by markmandel** [comment]
Also realised that https://github.com/googleforgames/agones/tree/master/examples/nodejs-simple is now broken, because it can't grab the package :confused:

**Comment by phumberdroz** [comment]
Is this fixed? 

Seems like there is a package now published under: https://www.npmjs.com/package/@googleforgames/agones

**Comment by markmandel** [comment]
This is not fixed yet. I need to navigate our internal tooling. I'm most of the way there. I'll make sure to round this out before the next release.

**Comment by markmandel** [comment]
> https://www.npmjs.com/package/@googleforgames/agones 

That is not an official release. @thisisnotapril we might want to look into this.

**Comment by markmandel** [comment]
Just noticed the documentation is actually wrong:
https://agones.dev/site/docs/guides/client-sdks/nodejs/

We don't mention the package is on Github, not npm

**Comment by markmandel** [comment]
https://www.npmjs.com/package/@google-cloud/agones-sdk

Check it out! Wanted to make sure this was in place for 1.4.0 RC release on Tuesday.

Updating the docs and example image :+1:

**Comment by phumberdroz** [comment]
Nice to see
